### ISSUE TITLE
Update Java 1.8

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-tourreservation#238]
## Description
Currently, java version is 1.7.

```xml
<java-version>1.7</java-version>
```

## Possible Solutions
We'll consider updating 1.8 at 5.1.0.RELEASE.

## Affects Version/s
* 5.0.0.RELEASE - 5.0.1.RELEASE
* 1.0.0.RELEASE - 1.0.3.RELEASE

## Fix Version/s
- [x] 5.1.0 on jpa
- [x] 5.1.0 on mybatis

## Issue Links
None

**Comment by kazuki43zoo** [comment]
porting on mybatis
