### ISSUE TITLE
Apply changes of MyBatis 3.3.0

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-tourreservation#281]
## Description
Refer to terasolunaorg/terasoluna-gfw-web-multi-blank#178

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.1.0 on mybatis3

## Issue Links
N/A

**Comment by btshimizukza** [comment]
Apply https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/commit/b5fbeb2e7117b5001b77feaa7b3ee7e6e8fb0e0a.
