### ISSUE TITLE
Apply Spring IO Platform 2.0

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/terasoluna-tourreservation#311]
## Description
Apply changes of Spring IO Platform 2.0.

* terasolunaorg/terasoluna-gfw#362
* terasolunaorg/guideline#1305 (Japanese only)

## Fix Version/s
- [ ] 5.1.0 on jpa
- [ ] 5.1.0 on mybatis

## Issue Links
N/A

**Comment by ikeyat** [comment]
No errors were found.
