### ISSUE TITLE
Add README.md for 5.1.x

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-tourreservation#364]
## Description
Add travis-ci badge for 5.1.x on README.md

## Possible Solutions
N/A

## Affects Version/s
N/A

## Fix Version/s
- [ ] 5.1.x on jpa
- [ ] 5.1.x on mybatis

**Comment by iwanagah** [comment]
I will update README.md after 5.1.0　release.

**Comment by ikeyat** [comment]
The title and article are confusing so I modified them and cleared milestone.
