### ISSUE TITLE
SQLFeatureNotSupportedException is output in the Postgresql JDBC at startup

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-tourreservation#380]
## Description
At executing `mvn tomcat:run`, the following error log is output (start-up is successful).
```
date:2016-04-06 10:54:34	thread:main	user:	X-Track:	level:ERROR	logger:jdbc.audit                                      	message:1. Connection.createClob()
java.sql.SQLFeatureNotSupportedException: org.postgresql.jdbc4.Jdbc4Connection.createClob() メソッドはまだ実装されていません。
```

## Possible Solutions
Add property file `hibernate.properties` in terasoluna-tourreservation-web resource folder, and add the following setting.

```properties
hibernate.jdbc.lob.non_contextual_creation = true
```

ref https://forum.hibernate.org/viewtopic.php?f=1&t=1033685&view=previous

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE_jpa
- [x] 5.1.1.RELEASE_jpa

## Issue Links
* none

**Comment by btyoshikawaa** [comment]
Please backport to 5.1.x JPA.
After that, please Investigate to whether this problem is also occur in gfw-func etc.., and create issue if it occurs.

**Comment by ikeyat** [comment]
@btkadotahr 
Please do https://github.com/terasolunaorg/terasoluna-tourreservation/issues/380#issuecomment-219913231

**Comment by btkadotahr** [comment]
Investigation of other projects has been completed.

**Comment by btyoshikawaa** [comment]
Thanks for your cooperation!
