### ISSUE TITLE
Correct copyright phrase

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/terasoluna-tourreservation#382]
## Description 
See https://github.com/terasolunaorg/terasoluna-gfw/issues/528

## Possible Solutions
See above.

## Affects Version/s
* 5.1.0.RELEASE
* 5.0.2.RELEASE
* 1.0.4.RELEASE

## Fix Version/s
- [x] 5.2.0.RELEASE on JPA
- [x] 5.1.1.RELEASE on JPA
- [x] 5.0.3.RELEASE on JPA
- [x] 1.0.5.RELEASE on JPA
- [ ] 5.2.0.RELEASE on MyBatis
- [ ] 5.1.1.RELEASE on MyBatis
- [ ] 5.0.3.RELEASE on MyBatis

## Issue Links
https://github.com/terasolunaorg/terasoluna-gfw/issues/528

**Comment by kazuki43zoo** [comment]
@btmiyashitasts Please apply for the [mybatis version](https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3).

**Comment by btshimizukza** [comment]
Thanks @btmiyashitasts !!
Please apply to mybatis version.
