### ISSUE TITLE
Separate pom.xml dependencies for app and common lib

### ISSUE THREAD

**Issue by bttanakagn** [terasolunaorg/terasoluna-tourreservation#391]
## Description
Refer to Issue Link

## Possible Solutions
Refer to Issue Link

## Affects Version/s
N/A

## Fix Version/s
- [x] 5.2.0_jpa
- [x] 5.2.0_mybatis3

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/508

**Comment by btyoshikawaa** [comment]
@bttanakagn 
Please porting to JPA.

**Comment by btyoshikawaa** [comment]
@bttanakagn 
Please check whether the same as the other repositories.

**Comment by btyoshikawaa** [comment]
@bttanakagn 
Please port to tourreservation-mybatis .
