### ISSUE TITLE
Resolve failed E2E tests for Spring IO Platform Athens-SR1

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-tourreservation#418]
## Description
2 E2E tests fail.

```console
Results :
Failed tests:
  testCustomerRegistCSRFToken(org.terasoluna.tourreservation.tourreserve.selenium.TokenCheckErrorTest): expected:<[Your Request is not acceptable.]> but was:<[type Status report]>
Tests in error:
  testLoginFailure(org.terasoluna.tourreservation.tourreserve.selenium.LogInLogOutTest): Unable to locate element: {"method":"id","selector":"loginError"}(..)

Tests run: 25, Failures: 1, Errors: 1, Skipped: 0
```
These failure caused when forward POST request to `view-controller` .

## Possible Solutions
* If view apply tiles layout, create Controller and forward to handler method.
* If else, forward to JSP file.

## Affects Version/s
* 5.3.0.RELEASE

## Fix Version/s
- [x] 5.3.0
- [x] 5.3.0 (rework for https://github.com/terasolunaorg/terasoluna-tourreservation/issues/418#issuecomment-274707412)
## Issue Links
* #416

**Comment by btideues** [comment]
When a CSRF token error occurs, an error message is displayed in Japanese because it transits to JSP in the state where the locale is not set.
It is necessary to correct the transition of error pages via Spring MVC.
