### ISSUE TITLE
Apply build java-version 1.8

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/terasoluna-tourreservation#432]
## Description
To align test conditions, change `java-version` to 1.8 .
This issue is maintenance task for release 2017 winter and later.

## Possible Solutions
* Change default of `java-version` property to 1.8 .
  - https://github.com/terasolunaorg/terasoluna-tourreservation/blob/5.0.x/terasoluna-tourreservation-parent/pom.xml#L156
  - https://github.com/terasolunaorg/terasoluna-tourreservation/blob/1.0.x/terasoluna-tourreservation-parent/pom.xml#L400

* Change travis jdk version to `oraclejdk8` only.
  - https://github.com/terasolunaorg/terasoluna-tourreservation/blob/5.0.x/.travis.yml#L4-L5
  - https://github.com/terasolunaorg/terasoluna-tourreservation/blob/1.0.x/.travis.yml#L4

## Affects Version/s
* 5.0.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [-] 5.3.0 now 1.8 !
- [-] 5.2.1 now 1.8 !
- [-] 5.1.2 now 1.8 !
- [x] 5.0.3
- [x] 1.0.6
- [x] 5.0.x on mybatis

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/528

**Comment by kazuki43zoo** [comment]
@btyanagawamg 

Please apply to 5.0.x on mybatis.

See https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3/blob/5.0.x/.travis.yml.
