### ISSUE TITLE
update copyright (2016 -> 2017)

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/terasoluna-tourreservation#446]
## Description
update copyright(2016->2017).

## Possible Solutions
Update the following resources.
- [x] license/header.txt
- [ ] *.java
- [x] terasoluna-tourreservation-web/src/main/webapp/WEB-INF/views/layout/footer.jsp

## Affects Version/s
* 5.3.0.RELEASE
* 5.2.1.RELEASE
* 1.0.6.RELEASE

## Fix Version/s
- [x] 5.3.0 JPA
- [x] 5.3.0 MyBatis3
- [x] 5.2.1 JPA
- [x] 5.2.1 MyBatis3
- [x] 1.0.6 JPA

## Issue Links
*

**Comment by kazuki43zoo** [comment]
done!!
