### ISSUE TITLE
Update SNAPSHOT version (after "2017 winter" release)

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/terasoluna-tourreservation#474]
## Description
Update version to 5.4.0-SNAPSHOT in master
Update version to 5.3.1-SNAPSHOT in 5.3.x
Update version to 5.2.2-SNAPSHOT in 5.2.x
Update version to 1.0.7-SNAPSHOT in 1.0.x

## Fix Version/s
-jpa
- [x] master
- [x] 5.3.x
- [x] 5.2.x
- [x] 1.0.x

-mybatis3
- [x] master
- [x] 5.3.x
- [x] 5.2.x

**Comment by bturamatuyu** [comment]
mybatis3 5.3.xにて、5.3.xのブランチの作成元がmybatis3/masterではなくjpa/masterとなっていたため、
ブランチを再作成しました。
それに伴い、mybatis3 5.3.x対応を行うため、Reopenします。

**Comment by bturamatuyu** [comment]
mybatis3 5.3.x対応が完了したため、Closeします。
