### ISSUE TITLE
Fixing the version of Firefox used by Travis CI (temporary solution)

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-tourreservation#496]
## Description
[Now Travis CI container image is changed.](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming)
As a result, the version of Firefox used by default changes, and Selenium webdriver 2.46 will fail.

## Possible Solutions
**temporary solution**
[Fix the version of Firefox.](https://docs.travis-ci.com/user/firefox)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

#### JPA
- [x] 5.4.0
- [x] 5.3.1
- [x] 5.2.2
- [x] 5.1.2
- [x] 5.0.3
- [x] 1.0.7
#### MyBatis
- [x] 5.4.0
- [x] 5.3.1
- [x] 5.2.2
- [x] 5.1.2
- [x] 5.0.3

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
As soon as possible, we should shift to selenium 3!

**Comment by itouyun** [comment]
Thank you for your work!!

**Comment by kazuki43zoo** [comment]
> As soon as possible, we should shift to selenium 3!

+1
