### ISSUE TITLE
Remove definition of trimTokens

### ISSUE THREAD

**Issue by bttsuchikawaf** [terasolunaorg/terasoluna-tourreservation#510]
## Description
Definition of  trimTokens=false  is default,  trimTokens=false  is not necessary.
Please see　[terasolunaorg/terasoluna-gfw-web-multi-blank #334](https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/334)

## Possible Solutions
 `pathMatcher` default is  `org.springframework.util.AntPathMatcher`.
AntPathMatcher has field "trimTokens" that defalt is false.
 for that reason, Remove it

[spring-mvc.xml]
```
 <mvc:path-matching path-matcher="pathMatcher" /> 

 <bean id="pathMatcher" class="org.springframework.util.AntPathMatcher"> 
     <property name="trimTokens" value="false" /> 
 </bean> 
```

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master) [in this repository]
- [x] 5.3.1 (5.3.x) [in this repository]
- [x] 5.4.0 (master) [terasoluna-tourreservation-mybatis3]
- [x] 5.3.1 (5.3.x) [terasoluna-tourreservation-mybatis3]

## Final Solution
do PossibleSolution

## Issue Links
* terasolunaorg/terasoluna-gfw-web-multi-blank#334
* terasolunaorg/terasoluna-gfw-web-blank#300
* terasolunaorg/guideline#2941

**Comment by itouyun** [comment]
@btoohashimc 
Thank you for your work!!
