### ISSUE TITLE
Local test stopped because of proxy auth

### ISSUE THREAD

**Issue by btkatoutmj** [terasolunaorg/terasoluna-tourreservation#522]
## Description
Selenium test stopped by proxy authentication window when tested in local PC that required proxy authentication to connect external network.
 If through a proxy authentication, the test is continued.

## Possible Solutions
FunctionTestSupport.java
```java
        if (driver == null) {
            FirefoxProfile profile = new FirefoxProfile();
            profile.setPreference("brouser.startup.homepage_override.mstone", "ignore");
            profile.setPreference("network.proxy.type", 0);
            driver = new FirefoxDriver(profile);
        }
```

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)

## Final Solution
(To be written later by project member)

## Issue Links
* terasolunaorg/terasoluna-gfw-functionaltest#432

**Comment by yoshikawaa** [comment]
@btkobayashirun 
Pleae confirm it is required to backport any branches.
