### ISSUE TITLE
Create new profile for Tomcat 8.5

### ISSUE THREAD

**Issue by btkatoutmj** [terasolunaorg/terasoluna-tourreservation#523]
## Description
Create new profile for Tomcat 8.5

## Possible Solutions
add `tomcat85-postgresql` profile

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.4.0 jpa
- [x] 5.4.0 mybatis
- [ ] 5.3.x jpa
- [ ] 5.3.x mybatis

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by btiidakua** [comment]
5.3.xへのバックポート対応のため、リオープンします。

**Comment by btiidakua** [comment]
5.3.xへのバックポートは不要となったため、クローズします。
