### ISSUE TITLE
There is no input check concerning the storable upper limit.

### ISSUE THREAD

**Issue by 5zm** [terasolunaorg/terasoluna-tourreservation#558]
## Description
There is no input check concerning the storable upper limit.

https://github.com/terasolunaorg/terasoluna-tourreservation/blob/master/terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managecustomer/CustomerForm.java

* line:91,92
```java
@NotEmpty
private String customerAdd;
```

If input over 300 charactoers, system error occuered.
300 charactoers is table definition.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affect versions
- 5.x.x.RELEASE

## Fix repositories
- [x] terasoluna-tourreservation
- [x] terasoluna-tourreservation-mybatis3

## Issue links
- #xx

**Comment by btkatoufm** [comment]
Test code was not fixed and reopened.
- [x] terasoluna-tourreservation
- [x] terasoluna-tourreservation-mybatis3
