### ISSUE TITLE
Place of {min} and {max}​ are incorrect on message.

### ISSUE THREAD

**Issue by 5zm** [terasolunaorg/terasoluna-tourreservation#559]
## Description
Place of {min} and {max}​ are incorrect on message.
These are reversed.

https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3/blob/master/terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties

* line:3
```properties
javax.validation.constraints.Size.message = {0}は{max}文字以上{min}文字以下で入力してください。
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0(master/JPA)
- [x] 5.4.2(5.4.x/JPA)
- [x] 5.5.0(master/MyBatis3)
- [x] 5.4.2(5.4.x/MyBatis3)

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by hirakuriy** [comment]
@btiwahorisu 
Thank you for the fix.
Please also fix terasoluna-tourreservation-mybatis3.

**Comment by btyanagawamg** [comment]
Please write Fix Version/s .

like ...

----

## Fix Version/s
- [ ] 5.5.0(master/JPA)
- [ ] 5.4.2(5.4.x/JPA)
- [ ] 5.5.0(master/MyBatis3)
- [ ] 5.4.2(5.4.x/MyBatis3)

----

And please backport for 5.4.x branch .

**Comment by hirakuriy** [comment]
> @hirakuriy
> @btiwahorisu
> 
> Please write Fix Version/s .
> 
> like ...
> 
> ## Fix Version/s
> * [ ]  5.5.0(master/JPA)
> * [ ]  5.4.2(5.4.x/JPA)
> * [ ]  5.5.0(master/MyBatis3)
> * [ ]  5.4.2(5.4.x/MyBatis3)
> 
> And please backport for 5.4.x branch .

@btyanagawamg 
Thank you for your pointing it out.
