### ISSUE TITLE
It contains unnecessary characters on message.

### ISSUE THREAD

**Issue by 5zm** [terasolunaorg/terasoluna-tourreservation#560]
## Description
It contains unnecessary characters on message.

https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3/blob/master/terasoluna-tourreservation-web/src/main/resources/ValidationMessages_ja.properties

```properties
javax.validation.constraints.Max.message = {0}大人の最大値は{value}です。
```

`'大人'` is unnecessary for message of `'@Max'`.

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0(master/JPA)
- [x] 5.4.2(5.4.x/JPA)
- [x] 5.5.0(master/MyBatis3)
- [x] 5.4.2(5.4.x/MyBatis3)

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by hirakuriy** [comment]
@btiwahorisu
Thank you for the fix.
Please also fix terasoluna-tourreservation-mybatis3.

**Comment by btyanagawamg** [comment]
@hirakuriy 
@btiwahorisu 

This ISSUE is needed backport for 5.4.x branch .
Please also see https://github.com/terasolunaorg/terasoluna-tourreservation/issues/559#issuecomment-426859659 .

**Comment by hirakuriy** [comment]
> @hirakuriy
> @btiwahorisu
> 
> This ISSUE is needed backport for 5.4.x branch .
> Please also see [#559 (comment)](https://github.com/terasolunaorg/terasoluna-tourreservation/issues/559#issuecomment-426859659) .

@btyanagawamg
Thank you for your pointing it out.
