### ISSUE TITLE
PDF can not be outputted when operating in Linux environment

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-tourreservation#575]
## Description
When trying to output PDF when operating under Linux environment, "File Not Found" error occurs.
This is because the path of the font file is unique to Windows in the JasperReports definition file used for PDF output.

https://github.com/terasolunaorg/terasoluna-tourreservation/blob/dd6958c86601e5885bf09defcf4890b64268cec0/terasoluna-tourreservation-web/src/main/webapp/WEB-INF/reports/reservationReportPdf.jrxml#L89

## Possible Solutions
* Change the font to one that does not depend on the environment.
* Enable to change the path of the font file. (ex. environment variable...)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.2_JPA
- [x] 5.4.2_MyBatis

## Issue Links
* #XXX

**Comment by hirakuriy** [comment]
要状況確認
