### ISSUE TITLE
[Spring 5.x] The method used was removed from spring-data-commons.

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-tourreservation#578]
## Description
The `findOne` and `delete` method of `CrudRepository` was deleted.
see terasolunaorg/terasoluna-gfw-functionaltest#731

## Possible Solutions
Please do the same correction terasolunaorg/terasoluna-gfw-functionaltest#731 .

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

### jpa
- [x] 5.5.0
### MyBatis
- [x] 5.5.1 (adjust method signeture to JPA)

## Final Solution
(To be written later by project member)

## Issue Links
* terasolunaorg/terasoluna-gfw-functionaltest#731

**Comment by yoshikawaa** [comment]
@btyanagawamg Need to refactor method signetures.
