### ISSUE TITLE
[Spring 5.x] Dropped JasperReports support

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-tourreservation#582]
## Description
From Spring 5, `JasperReports` is no longer supported. (class that used to support `JasperReports` was deleted)

* [[SPR-13294] Drop JasperReports support - Spring JIRA](https://jira.spring.io/browse/SPR-13294)

##### Deleted package)
* `org.springframework.ui.jasperreports`
* `org.springframework.web.servlet.view.jasperreports`

#### Temporary correspondence
Delete `JasperReports` bean .

#### Full correspondence

Please take one of the following measures as TERASOLUNA.
- Supports JasperReports as TERASOLUNA.
- Change to alternative means supported by Spring other than JasperReports.
- Exclude JasperReports from support.

Also, please do appropriate modification as TERASOLUNA sample application(terasoluna-tourreservation) .

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

##### JPA
- [x] 1.6.x(master)
##### MyBatis
- [x] 1.6.x(master)

##### JPA
- [x] 1.6.x(master)
##### MyBatis
- [x] 1.6.x(master)

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
Fix changes::
* JasperReports -> OpenPdf & Acrobat Fields
* Create custom View class and test case.
