### ISSUE TITLE
[Dozer 6.x] The Application of Copying By Object Reference

### ISSUE THREAD

**Issue by btshuugna** [terasolunaorg/terasoluna-tourreservation#586]
## Description
When the mapping between two collection, and the reserveList's fetchtype is lazy, that will get the size of an uninitialized collection, the following error has occurred. 
```
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.terasoluna.tourreservation.domain.model.Customer.reserveList, could not initialize proxy - no Session
```
**The reason is that the classes want to be copied by reference，but there is no effect when the classes defined in the configuration block in the mapping.xml file.(There is the same problom in the terasoluna-tourreservation-mybatis3)**
```
  <configuration>
      <copy-by-references>
          <copy-by-reference>
	      org.terasoluna.tourreservation.domain.model.*
          </copy-by-reference>
      </copy-by-references>
  </configuration>
```

But at dozer 6.2, the above error will not happen, copying an object by reference, the mapping is ok.
Error will occur only after dozer 6.3.
At dozer 6.2, parsing the XML file the configuration is :
```
  copyByReferences=com.github.dozermapper.core.classmap.CopyByReferenceContainer@2292610c[
  copyByReferences=[com.github.dozermapper.core.classmap.CopyByReference@524f1cef[
  mask=org.terasoluna.tourreservation.domain.model.*
  pattern=org\.terasoluna\.tourreservation\.domain\.model\..*?
]]
```
At dozer 6.3, parsing the XML file the configuration is :
```
  copyByReferences=com.github.dozermapper.core.classmap.CopyByReferenceContainer@2292610c[
  copyByReferences=[com.github.dozermapper.core.classmap.CopyByReference@524f1cef[
  mask=
		org.terasoluna.tourreservation.domain.model.*
      
  pattern=
		org\.terasoluna\.tourreservation\.domain\.model\..*?
      
]]
```

**The real reason is that from dozer 6.3, the way of parsing the XML file has changed(DOM (Document Object Model) ==> JAXB).**
see migration :
https://github.com/DozerMapper/dozer/blob/master/docs/asciidoc/migration/v62-to-v63.adoc
see PR :
https://github.com/DozerMapper/dozer/pull/596
```
4. dozer.xml.use-jaxb-mapping-engine enabled by default
JAXB is used by default, if this causes issues, it can be disabled via:
    -Ddozer.xml.use-jaxb-mapping-engine=false

And the following is deprecated:
    com.github.dozermapper.core.loader.xml
In favour of:
    com.github.dozermapper.core.builder.xml
```
The source is that
SettingsDefaults :
```
public static final Boolean USE_JAXB_MAPPING_ENGINE = true;
```
DozerBeanMapperBuilder :
```
if (settings.getUseJaxbMappingEngine()) {
    mappingsFileData.addAll(buildXmlMappings(beanContainer, destBeanCreator, propertyDescriptorFactory, elEngine));
} else {
    XMLParser xmlParser = new XMLParser(beanContainer, destBeanCreator, propertyDescriptorFactory);
    XMLParserFactory xmlParserFactory = new XMLParserFactory(beanContainer);
    mappingsFileData.addAll(readXmlMappings(xmlParserFactory, xmlParser));
    mappingsFileData.addAll(loadFromFiles(mappingFiles, xmlParserFactory, xmlParser, beanContainer));
}
```
## Possible Solutions

Dozer supports copying an object by reference.
see Documentation
https://dozermapper.github.io/gitbook/documentation/copybyreference.html

At dozer 6.3

Solutions 1:
Using the class level to copying an object by reference.
```
  <configuration>
    <copy-by-references>
      <copy-by-reference>org.terasoluna.tourreservation.domain.model.*</copy-by-reference>
    </copy-by-references>
  </configuration>
```
Solutions 2:
Using the field level to copying an object by reference.
```
<field copy-by-reference="true">
    <a>copyByReference</a>
    <b>copyByReferencePrime</b>
</field>
```

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
  - [x] master(5.5.0/jpa)
  - [x] master(5.5.0/MyBatis)

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by btyanagawamg** [comment]
already finished .
