### ISSUE TITLE
[Spring Boot 2.1] [Lombok] Restore Lombok version (to depend on Spring IO definition)

### ISSUE THREAD

**Issue by btkousil** [terasolunaorg/terasoluna-tourreservation#588]
related #602 

[Spring Boot 2.1.2.RELEASE](https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/htmlsingle/) use Lombok 1.18.4 .

----

## Description
In order to solve lombok 1.16.22 's bug which introduced by Spring Boot 2.0.4(see #585 ) , Custom lombok's version to 1.18.2  in tourreservation.
When Spring boot upgrade its dependence version of lombok, delete the setting in pom.xml

## Possible Solutions
commit 650b87b41d0087d93bb4778d26a578a570f0ef1e

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.1 (jpa/master)
- [x] 5.5.1 (mybatis3/master)

## Final Solution
(To be written later by project member)

**Comment by btyanagawamg** [comment]
@hirakuriy 
@bttanakaysd 
Since this ISSUE will be done after the version of Lombok defined by Spring IO has been changed, it will not be done immediately .
