### ISSUE TITLE
Resolve deprecated API

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/terasoluna-tourreservation#614]
## Description
Resolve deprecated API (Eclipse warnings)

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.5.1 (master)
- [x] 5.5.1 (mybatis3/master)
- [x] 5.4.2 (5.4.x)
- [x] 5.4.2 (mybatis3/5.4.x)

## Issue Links
- #XXX

**Comment by bthabukar** [comment]
- 5.5.1 (mybatis3/master)
There is an import that is not used for [ManageReservationController.java#42](https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3/blob/master/terasoluna-tourreservation-web/src/main/java/org/terasoluna/tourreservation/app/managereservation/ManageReservationController.java#L42) .
I need to fix it.
