### ISSUE TITLE
Schema location for Spring can be replaced from `http` to `https`.

### ISSUE THREAD

**Issue by hirakuriy** [terasolunaorg/terasoluna-tourreservation#624]
## Description
The [SPR-13499](https://github.com/spring-projects/spring-framework/issues/18077) changes.
Schema location for Spring can be replaced from `http` to `https` in Bean definition files (ex. [spring-mvc.xml](https://github.com/terasolunaorg/terasoluna-gfw-web-blank/blob/master/src/main/resources/META-INF/spring/spring-mvc.xml#L8-L12) ).

Please see spring-projects/spring-framework#22504 .
## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
(To be written later by project member)
- [x] 5.6.0 (master)
- [x] 5.6.0 (mybatis3/master)
- [ ] 5.5.2 (5.5.x)
- [ ] 5.5.2 (mybatis3/5.5.x)
- [x] 5.4.2 (5.4.x)
- [x] 5.4.2 (mybatis3/5.4.x)

## Issue Links
- https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/402

**Comment by btkobayashirun** [comment]
Closed because no backport is required.
