### ISSUE TITLE
Upgrade JasperReports

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-tourreservation#630]
## Description

We use old JasperReports version ([3.5.1](https://github.com/terasolunaorg/terasoluna-tourreservation/blob/5.4.1.RELEASE/pom.xml#L282)) .

## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.2 (5.4.x)
- [x] 5.4.2 (mybatis3/5.4.x)

## Issue Links
- #XXX

**Comment by yoshikawaa** [comment]
Upgraded to verified 5.2.0.
The latest upgrade to 6.x will be considered separately. (@btyanagawamg )
