### ISSUE TITLE
Reflect:Update PostgreSQL and Firefox version used at Travis CI

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-tourreservation#678]
## Original Issue
- Reflect https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/863

## Description
Update PostgreSQL and Firefox version used at Travis CI

## Fix repositories
- [x] terasoluna-tourreservation
- [x] terasoluna-tourreservation-mybatis3

## Issue links
- #xx

**Comment by btiwahorisu** [comment]
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/863#issuecomment-745091742
