### ISSUE TITLE
Reflect:Update the version of maven-plugin

### ISSUE THREAD

**Issue by btootomoyuk** [terasolunaorg/terasoluna-tourreservation#686]
## Original Issue
> Links to the original issues.

- Reflect https://github.com/terasolunaorg/terasoluna-gfw/issues/1083

## Possible Solution
> Please write ideas or candidates of solutions for the problem if you have.
> **If it is an example, please enter a description such as "For example".**

Take the following actions:
- Upgrade the plugin version
- Remove unnecessary plugins.
- Change `com.google.code:maven-license-plugin` to `com.mycila:license-maven-plugin` as described in https://github.com/terasolunaorg/terasoluna-gfw/issues/600.
- Modify the variable name of the plugin version to be `groupId.artifactId.pugin.version`.

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-tourreservation
- [x] terasoluna-tourreservation-mybatis3

**Comment by btonokit** [comment]
I thought that plugins that were set in the blank project but were not used should be deleted, but from the following points, I decided to set all the plugins that are set in the blank project. Therefore, it will be reopened.
https://github.com/terasolunaorg/terasoluna-tourreservation/pull/716#discussion_r680713364
