### ISSUE TITLE
Backport:Update PostgreSQL and Firefox version used at Travis CI

### ISSUE THREAD

**Issue by btonokit** [terasolunaorg/terasoluna-tourreservation#689]
## Original Issue
> Links to the original issues.

- Backport #678

## Fix repositories
> Repositories to fix with this issue.

- [x] terasoluna-tourreservation
- [x] terasoluna-tourreservation-mybatis3

**Comment by btiwahorisu** [comment]
add backport.
https://github.com/terasolunaorg/terasoluna-tourreservation/issues/678#issuecomment-747116810
