### ISSUE TITLE
Source files committed in non-UTF8 format

### ISSUE THREAD

**Issue by zaheernanji** [terasolunaorg/terasoluna-tourreservation#83]
Since source files are being committed in Cp1252 format, test data assert values in JUnit test cases are showing junk values due to which test cases are failing. 
Would suggest converting source files to UTF8 format before commit.

**Comment by btshimizukza** [comment]
Hi @zaheernanji ,

Could you please feedback for this issue ?

**Comment by kazuki43zoo** [comment]
Hi @zaheernanji, 

No reply. I've close this, however you can reopen anytime.
